import sys
import re

translations_file = r"c:\Users\Jatin\OneDrive\Desktop\jeevansetuaiproject\Sama-Social-Hackathon-project\src\utils\translations.ts"

# Define the precise regional translations for the missing languages
new_translations = {
    "gu": {
        "jsExplore": "સ્થાનિક કામની તકો શોધો",
        "jsExploreDesc": "દૈનિક વેતન, ખેતીકામ અને અન્ય કામો શોધો અને અરજી કરો.",
        "jsAadhaarInspected": "100% આધાર પ્રમાણિત",
        "jsSearchPlaceholder": "કામનો પ્રકાર, નોકરીદાતા અથવા સ્થાન શોધો...",
        "jsListening": "સાંભળી રહ્યું છે...",
        "jsVerifiedEmployers": "માત્ર પ્રમાણિત નોકરીદાતાઓ",
        "catAll": "બધા",
        "catAgriculture": "ખેતી",
        "catCarpenter": "સુથાર",
        "catPainter": "પેઇન્ટર",
        "catElectrician": "ઇલેક્ટ્રિશિયન",
        "catPlumber": "પ્લમ્બર",
        "catDriver": "ડ્રાઈવર",
        "catDailyWage": "દૈનિક વેતન",
        "jsLoadingJobs": "નોકરીઓ લોડ થઈ રહી છે...",
        "jsEmployerTrust": "નોકરીદાતા પર વિશ્વાસ",
        "jsEmployer": "નોકરીદાતા",
        "jsGovtOk": "સરકાર માન્ય",
        "jsAway": "દૂર",
        "jsAppSubmitted": "અરજી સબમિટ કરી",
        "jsStopRecording": "રેકોર્ડિંગ બંધ કરો",
        "jsApplyVoice": "અવાજ દ્વારા અરજી કરો",
        "jsApplyManual": "મેન્યુઅલ અરજી કરો",
        "jsSayToApply": '"મારે અરજી કરવી છે" કહો અથવા તમારી લાયકાત જણાવો...',
        "jsNoJobsFound": "કોઈ નોકરીઓ મળી નથી. કૃપા કરીને શોધ બદલો.",
        "jsFailedToFetch": "નોકરીઓ મેળવવામાં નિષ્ફળ",
        "jsFailedToApply": "અરજી કરવામાં નિષ્ફળ",
        "fhTitle": "સ્માર્ટ કૃષિ હબ",
        "fhDesc": "પ્રમાણિત ખેતમજૂરો શોધો, મશીનરી ભાડે લો, બજારના ભાવો તપાસો.",
        "fhSeasonal": "મોસમી માંગ પ્રમાણિત",
        "fhWeatherAdv": "હવામાન સલાહ",
        "fhClearSky": "સ્વચ્છ આકાશ • લણણી માટે ઉત્તમ",
        "fhNoRainfall": "આગામી 5 દિવસ વરસાદની અપેક્ષા નથી. લણણી પૂર્ણ કરો.",
        "fhPriceStabilization": "કિંમત સ્થિરીકરણ ગેરંટી",
        "fhPriceDesc": "જીવનસેતુ સ્માર્ટ કરાર દ્વારા કૃષિ સેવાઓ પર નજર રાખે છે જેથી ભાવો ન વધે.",
        "fhHireLaborers": "ખેતમજૂર ભાડે લો",
        "fhEquipmentRentals": "સાધનો ભાડે",
        "fhMandiPrices": "સ્થાનિક બજારના ભાવો",
        "fhLoading": "ડેટા લોડ થઈ રહ્યો છે...",
        "fhExp": "અનુભવ",
        "fhRateRequired": "જરૂરી દર",
        "fhProximity": "નજીકતા",
        "fhLaborerBooked": "મજૂર બુક થયો",
        "fhBooking": "બુકિંગ...",
        "fhBookLaborer": "મજૂર બુક કરો",
        "fhOwner": "માલિક",
        "fhRentalRate": "ભાડાનો દર",
        "fhLocation": "સ્થાન",
        "fhCurrentlyRented": "હાલમાં ભાડે છે",
        "fhRentEquipment": "સાધનો ભાડે લો",
        "fhRenting": "ભાડે લઈ રહ્યા છીએ...",
        "fhMandiDesc": "નીચે સ્થાનિક બજારોના પ્રમાણિત દરો છે.",
        "fhCropName": "પાકનું નામ",
        "fhSonipatMandi": "સોનીપત બજાર",
        "fhNarelaMandi": "નરેલા બજાર",
        "fhRohtakMandi": "રોહતક બજાર",
        "fhDailyTrend": "દૈનિક વલણ",
        "fhUpward": "▲ ઉપર",
        "fhDownward": "▼ નીચે",
        "vsSecureGov": "સુરક્ષિત સરકારી API સેન્ડબોક્સ",
        "vsTitle": "આધાર ઓળખ ચકાસણી",
        "vsDesc": "ઉચ્ચ ટ્રસ્ટ સ્કોર અને સારી નોકરીઓ માટે OTP સાથે તમારી ઓળખ ચકાસો.",
        "vsWhyVerify": "શા માટે ઓળખ ચકાસવી?",
        "vsZeroScam": "શૂન્ય કૌભાંડ પ્લેટફોર્મ તપાસ",
        "vsZeroScamDesc": "ખાતરી કરે છે કે દરેક વપરાશકર્તા પાસે માત્ર એક જ ખાતું છે.",
        "vsTrustScore": "ટ્રસ્ટ સ્કોર વધારો",
        "vsTrustScoreDesc": "આધાર ચકાસણી ટ્રસ્ટ સ્કોરમાં તરત જ +25 પોઈન્ટનો વધારો કરે છે.",
        "vsEmployerPriority": "નોકરીદાતા પ્રાધાન્ય",
        "vsEmployerPriorityDesc": "પ્રમાણિત કામદારો નોકરીદાતાઓને પહેલા દેખાય છે.",
        "vsStep1": "પગલું 1: 12-અંકનો આધાર દાખલ કરો",
        "vsAadhaarNum": "આધાર નંબર",
        "vsAadhaarPlaceholder": "XXXX XXXX XXXX",
        "vsNoStore": "અમે તમારો આધાર સાચવતા નથી. સીધી CIDR ચકાસણી.",
        "vsRequestOtp": "OTP માટે વિનંતી કરો",
        "vsStep2": "પગલું 2: SMS OTP દાખલ કરો",
        "vsOtpSent": "તમારા આધાર-લિંક કરેલ મોબાઈલ નંબર પર એક કોડ મોકલવામાં આવ્યો છે",
        "vsUseCode": "સિમ્યુલેટ કરવા માટે કોડ વાપરો",
        "vsSimulate": "",
        "vs6DigitOtp": "6-અંકનો OTP",
        "vsEnterOtpPlaceholder": "6-અંકનો OTP દાખલ કરો",
        "vsGoBack": "પાછા જાઓ",
        "vsVerifyMatch": "ચકાસો અને ઓળખ મેળવો",
        "vsConnecting": "CIDR સેન્ડબોક્સ સાથે જોડાઈ રહ્યા છીએ",
        "vsInspecting": "બાયોમેટ્રિક ડેટા અને નામ ચકાસી રહ્યા છીએ. કૃપા કરીને રાહ જુઓ...",
        "vsConfirmed": "આધાર ઓળખની પુષ્ટિ થઈ ગઈ!",
        "vsCongrats": "અભિનંદન! તમારી પ્રોફાઇલ પર સરકારી ચકાસણી બેજ ઉમેરવામાં આવ્યો છે.",
        "vsBaseTrust": "મૂળ ટ્રસ્ટ સ્કોર:",
        "vsNewTrust": "નવો ટ્રસ્ટ સ્કોર:",
        "vsReturn": "ડેશબોર્ડ પર પાછા ફરો",
        "vsErrAadhaarLen": "આધાર નંબર બરાબર 12 અંકોનો હોવો જોઈએ.",
        "vsErrReqOtp": "OTP વિનંતી નિષ્ફળ",
        "vsErrOtpLen": "OTP 6 અંકોનો હોવો જોઈએ.",
        "vsErrInvalidOtp": "અમાન્ય OTP",
        "appTopBanner": "અધિકૃત સરકારી ટેકનોલોજી સેન્ડબોક્સ. 100% સુરક્ષિત.",
        "appLogoSubtitle": "સરકારી રોજગાર ઇકોસિસ્ટમ"
    },
    "pa": {
        "jsExplore": "ਸਥਾਨਕ ਕੰਮ ਦੇ ਮੌਕੇ ਲੱਭੋ",
        "jsExploreDesc": "ਰੋਜ਼ਾਨਾ ਦਿਹਾੜੀਦਾਰ ਅਤੇ ਖੇਤੀ ਦੇ ਕੰਮ ਲੱਭੋ ਅਤੇ ਅਰਜ਼ੀ ਦਿਓ।",
        "jsAadhaarInspected": "100% ਆਧਾਰ ਪ੍ਰਮਾਣਿਤ",
        "jsSearchPlaceholder": "ਕੰਮ ਦੀ ਕਿਸਮ, ਰੁਜ਼ਗਾਰਦਾਤਾ ਜਾਂ ਸਥਾਨ ਖੋਜੋ...",
        "jsListening": "ਸੁਣ ਰਿਹਾ ਹੈ...",
        "jsVerifiedEmployers": "ਸਿਰਫ਼ ਪ੍ਰਮਾਣਿਤ ਰੁਜ਼ਗਾਰਦਾਤਾ",
        "catAll": "ਸਾਰੇ",
        "catAgriculture": "ਖੇਤੀਬਾੜੀ",
        "catCarpenter": "ਤਰਖਾਣ",
        "catPainter": "ਪੇਂਟਰ",
        "catElectrician": "ਬਿਜਲੀ ਵਾਲਾ",
        "catPlumber": "ਪਲੰਬਰ",
        "catDriver": "ਡਰਾਈਵਰ",
        "catDailyWage": "ਦਿਹਾੜੀ",
        "jsLoadingJobs": "ਨੌਕਰੀਆਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ...",
        "jsEmployerTrust": "ਰੁਜ਼ਗਾਰਦਾਤਾ ਟਰੱਸਟ",
        "jsEmployer": "ਰੁਜ਼ਗਾਰਦਾਤਾ",
        "jsGovtOk": "ਸਰਕਾਰ ਪ੍ਰਵਾਨਿਤ",
        "jsAway": "ਦੂਰ",
        "jsAppSubmitted": "ਅਰਜ਼ੀ ਜਮ੍ਹਾਂ ਹੋ ਗਈ",
        "jsStopRecording": "ਰਿਕਾਰਡਿੰਗ ਰੋਕੋ",
        "jsApplyVoice": "ਆਵਾਜ਼ ਨਾਲ ਅਰਜ਼ੀ ਦਿਓ",
        "jsApplyManual": "ਦਸਤੀ ਅਰਜ਼ੀ ਦਿਓ",
        "jsSayToApply": '"ਮੈਂ ਅਰਜ਼ੀ ਦੇਣਾ ਚਾਹੁੰਦਾ ਹਾਂ" ਕਹੋ ਜਾਂ ਆਪਣੀ ਯੋਗਤਾ ਦੱਸੋ...',
        "jsNoJobsFound": "ਕੋਈ ਨੌਕਰੀ ਨਹੀਂ ਮਿਲੀ। ਕਿਰਪਾ ਕਰਕੇ ਖੋਜ ਬਦਲੋ।",
        "jsFailedToFetch": "ਨੌਕਰੀਆਂ ਪ੍ਰਾਪਤ ਕਰਨ ਵਿੱਚ ਅਸਫਲ",
        "jsFailedToApply": "ਅਰਜ਼ੀ ਦੇਣ ਵਿੱਚ ਅਸਫਲ",
        "fhTitle": "ਸਮਾਰਟ ਖੇਤੀ ਹੱਬ",
        "fhDesc": "ਪ੍ਰਮਾਣਿਤ ਖੇਤ ਮਜ਼ਦੂਰ ਲੱਭੋ, ਮਸ਼ੀਨਰੀ ਕਿਰਾਏ 'ਤੇ ਲਓ, ਮੰਡੀ ਦੇ ਭਾਅ ਚੈੱਕ ਕਰੋ।",
        "fhSeasonal": "ਮੌਸਮੀ ਮੰਗ ਪ੍ਰਮਾਣਿਤ",
        "fhWeatherAdv": "ਮੌਸਮ ਦੀ ਸਲਾਹ",
        "fhClearSky": "ਸਾਫ਼ ਅਸਮਾਨ • ਵਾਢੀ ਲਈ ਵਧੀਆ",
        "fhNoRainfall": "ਅਗਲੇ 5 ਦਿਨਾਂ ਤੱਕ ਮੀਂਹ ਦੀ ਕੋਈ ਸੰਭਾਵਨਾ ਨਹੀਂ। ਵਾਢੀ ਪੂਰੀ ਕਰੋ।",
        "fhPriceStabilization": "ਕੀਮਤ ਸਥਿਰਤਾ ਗਰੰਟੀ",
        "fhPriceDesc": "ਜੀਵਨਸੇਤੂ ਸਮਾਰਟ ਕੰਟਰੈਕਟਸ ਰਾਹੀਂ ਕੀਮਤਾਂ ਨੂੰ ਕੰਟਰੋਲ ਕਰਦਾ ਹੈ।",
        "fhHireLaborers": "ਖੇਤ ਮਜ਼ਦੂਰ ਰੱਖੋ",
        "fhEquipmentRentals": "ਉਪਕਰਣ ਕਿਰਾਏ 'ਤੇ",
        "fhMandiPrices": "ਮੰਡੀ ਦੇ ਭਾਅ",
        "fhLoading": "ਡਾਟਾ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
        "fhExp": "ਤਜਰਬਾ",
        "fhRateRequired": "ਲੋੜੀਂਦੀ ਦਰ",
        "fhProximity": "ਨੇੜਤਾ",
        "fhLaborerBooked": "ਮਜ਼ਦੂਰ ਬੁੱਕ ਹੋਇਆ",
        "fhBooking": "ਬੁਕਿੰਗ...",
        "fhBookLaborer": "ਮਜ਼ਦੂਰ ਬੁੱਕ ਕਰੋ",
        "fhOwner": "ਮਾਲਕ",
        "fhRentalRate": "ਕਿਰਾਏ ਦੀ ਦਰ",
        "fhLocation": "ਸਥਾਨ",
        "fhCurrentlyRented": "ਵਰਤਮਾਨ ਵਿੱਚ ਕਿਰਾਏ 'ਤੇ",
        "fhRentEquipment": "ਉਪਕਰਣ ਕਿਰਾਏ 'ਤੇ ਲਓ",
        "fhRenting": "ਕਿਰਾਏ 'ਤੇ ਲੈ ਰਿਹਾ ਹੈ...",
        "fhMandiDesc": "ਹੇਠਾਂ ਸਥਾਨਕ ਮੰਡੀਆਂ ਦੇ ਪ੍ਰਮਾਣਿਤ ਦਰ ਹਨ।",
        "fhCropName": "ਫ਼ਸਲ ਦਾ ਨਾਮ",
        "fhSonipatMandi": "ਸੋਨੀਪਤ ਮੰਡੀ",
        "fhNarelaMandi": "ਨਰੇਲਾ ਮੰਡੀ",
        "fhRohtakMandi": "ਰੋਹਤਕ ਮੰਡੀ",
        "fhDailyTrend": "ਰੋਜ਼ਾਨਾ ਰੁਝਾਨ",
        "fhUpward": "▲ ਉੱਪਰ",
        "fhDownward": "▼ ਹੇਠਾਂ",
        "vsSecureGov": "ਸੁਰੱਖਿਅਤ ਸਰਕਾਰੀ API ਸੈਂਡਬਾਕਸ",
        "vsTitle": "ਆਧਾਰ ਪਛਾਣ ਤਸਦੀਕ",
        "vsDesc": "ਉੱਚ ਟਰੱਸਟ ਸਕੋਰ ਲਈ OTP ਰਾਹੀਂ ਪਛਾਣ ਤਸਦੀਕ ਕਰੋ।",
        "vsWhyVerify": "ਪਛਾਣ ਤਸਦੀਕ ਕਿਉਂ ਕਰੀਏ?",
        "vsZeroScam": "ਜ਼ੀਰੋ ਘੁਟਾਲਾ ਪਲੇਟਫਾਰਮ",
        "vsZeroScamDesc": "ਹਰੇਕ ਉਪਭੋਗਤਾ ਦਾ ਸਿਰਫ਼ ਇੱਕ ਖਾਤਾ ਹੁੰਦਾ ਹੈ।",
        "vsTrustScore": "ਟਰੱਸਟ ਸਕੋਰ ਵਾਧਾ",
        "vsTrustScoreDesc": "ਆਧਾਰ ਤਸਦੀਕ ਤੁਰੰਤ ਟਰੱਸਟ ਸਕੋਰ ਵਿੱਚ +25 ਪੁਆਇੰਟ ਵਧਾਉਂਦਾ ਹੈ।",
        "vsEmployerPriority": "ਰੁਜ਼ਗਾਰਦਾਤਾ ਤਰਜੀਹ",
        "vsEmployerPriorityDesc": "ਪ੍ਰਮਾਣਿਤ ਕਾਮੇ ਪਹਿਲਾਂ ਦਿਖਾਈ ਦਿੰਦੇ ਹਨ।",
        "vsStep1": "ਕਦਮ 1: 12-ਅੰਕ ਦਾ ਆਧਾਰ ਦਰਜ ਕਰੋ",
        "vsAadhaarNum": "ਆਧਾਰ ਨੰਬਰ",
        "vsAadhaarPlaceholder": "XXXX XXXX XXXX",
        "vsNoStore": "ਅਸੀਂ ਆਧਾਰ ਸਟੋਰ ਨਹੀਂ ਕਰਦੇ। ਸਿੱਧਾ CIDR ਕਨੈਕਸ਼ਨ।",
        "vsRequestOtp": "OTP ਦੀ ਬੇਨਤੀ ਕਰੋ",
        "vsStep2": "ਕਦਮ 2: SMS OTP ਦਰਜ ਕਰੋ",
        "vsOtpSent": "ਤੁਹਾਡੇ ਆਧਾਰ-ਲਿੰਕ ਕੀਤੇ ਮੋਬਾਈਲ ਨੰਬਰ 'ਤੇ ਕੋਡ ਭੇਜਿਆ ਗਿਆ ਹੈ",
        "vsUseCode": "ਸਿਮੂਲੇਟ ਕਰਨ ਲਈ ਕੋਡ ਦੀ ਵਰਤੋਂ ਕਰੋ",
        "vsSimulate": "",
        "vs6DigitOtp": "6-ਅੰਕ ਦਾ OTP",
        "vsEnterOtpPlaceholder": "6-ਅੰਕ ਦਾ OTP ਦਰਜ ਕਰੋ",
        "vsGoBack": "ਵਾਪਸ ਜਾਓ",
        "vsVerifyMatch": "ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਮੇਲ ਕਰੋ",
        "vsConnecting": "CIDR ਸੈਂਡਬਾਕਸ ਨਾਲ ਜੁੜ ਰਿਹਾ ਹੈ",
        "vsInspecting": "ਬਾਇਓਮੀਟ੍ਰਿਕ ਡਾਟਾ ਦੀ ਜਾਂਚ ਹੋ ਰਹੀ ਹੈ...",
        "vsConfirmed": "ਆਧਾਰ ਪਛਾਣ ਦੀ ਪੁਸ਼ਟੀ ਹੋਈ!",
        "vsCongrats": "ਵਧਾਈਆਂ! ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ 'ਤੇ ਸਰਕਾਰੀ ਬੈਜ ਸ਼ਾਮਲ ਕੀਤਾ ਗਿਆ ਹੈ।",
        "vsBaseTrust": "ਮੂਲ ਟਰੱਸਟ ਸਕੋਰ:",
        "vsNewTrust": "ਨਵਾਂ ਟਰੱਸਟ ਸਕੋਰ:",
        "vsReturn": "ਡੈਸ਼ਬੋਰਡ 'ਤੇ ਵਾਪਸ ਜਾਓ",
        "vsErrAadhaarLen": "ਆਧਾਰ ਨੰਬਰ 12 ਅੰਕਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।",
        "vsErrReqOtp": "OTP ਬੇਨਤੀ ਫੇਲ੍ਹ",
        "vsErrOtpLen": "OTP 6 ਅੰਕਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।",
        "vsErrInvalidOtp": "ਗਲਤ OTP",
        "appTopBanner": "ਅਧਿਕਾਰਤ ਸਰਕਾਰੀ ਤਕਨਾਲੋਜੀ ਪਹਿਲਕਦਮੀ. 100% ਸੁਰੱਖਿਅਤ।",
        "appLogoSubtitle": "ਸਰਕਾਰੀ ਰੁਜ਼ਗਾਰ ਈਕੋਸਿਸਟਮ"
    },
    "bn": {
        "jsExplore": "স্থানীয় কাজের সুযোগ খুঁজুন",
        "jsExploreDesc": "দৈনিক মজুরি, খামার এবং কারিগরের কাজ খুঁজুন এবং আবেদন করুন।",
        "jsAadhaarInspected": "১০০% আধার যাচাইকৃত",
        "jsSearchPlaceholder": "কাজের ধরণ, নিয়োগকর্তা বা অবস্থান খুঁজুন...",
        "jsListening": "শুনছি...",
        "jsVerifiedEmployers": "শুধুমাত্র যাচাইকৃত নিয়োগকর্তা",
        "catAll": "সব",
        "catAgriculture": "কৃষি",
        "catCarpenter": "ছুতার",
        "catPainter": "রংমিস্ত্রি",
        "catElectrician": "ইলেকট্রিশিয়ান",
        "catPlumber": "প্লাম্বার",
        "catDriver": "চালক",
        "catDailyWage": "দৈনিক মজুরি",
        "jsLoadingJobs": "চাকরি লোড হচ্ছে...",
        "jsEmployerTrust": "নিয়োগকর্তার উপর আস্থা",
        "jsEmployer": "নিয়োগকর্তা",
        "jsGovtOk": "সরকার অনুমোদিত",
        "jsAway": "দূরে",
        "jsAppSubmitted": "আবেদন জমা দেওয়া হয়েছে",
        "jsStopRecording": "রেকর্ডিং থামান",
        "jsApplyVoice": "ভয়েস দিয়ে আবেদন করুন",
        "jsApplyManual": "ম্যানুয়াল আবেদন করুন",
        "jsSayToApply": '"আমি আবেদন করতে চাই" বলুন বা আপনার যোগ্যতা জানান...',
        "jsNoJobsFound": "কোন চাকরি পাওয়া যায়নি। অনুসন্ধান পরিবর্তন করুন।",
        "jsFailedToFetch": "চাকরি আনতে ব্যর্থ",
        "jsFailedToApply": "আবেদন করতে ব্যর্থ",
        "fhTitle": "স্মার্ট কৃষি হাব",
        "fhDesc": "যাচাইকৃত কৃষিশ্রমিক খুঁজুন, যন্ত্রপাতি ভাড়া নিন, বাজারের দাম পরীক্ষা করুন।",
        "fhSeasonal": "মৌসুমি চাহিদা যাচাইকৃত",
        "fhWeatherAdv": "আবহাওয়ার পরামর্শ",
        "fhClearSky": "পরিষ্কার আকাশ • ফসল কাটার জন্য উপযুক্ত",
        "fhNoRainfall": "আগামী ৫ দিন বৃষ্টির সম্ভাবনা নেই। ফসল কাটা শেষ করুন।",
        "fhPriceStabilization": "মূল্য স্থিতিশীলতার গ্যারান্টি",
        "fhPriceDesc": "জীবনসেতু স্মার্ট চুক্তির মাধ্যমে মূল্য স্থিতিশীল রাখে।",
        "fhHireLaborers": "কৃষিশ্রমিক নিয়োগ দিন",
        "fhEquipmentRentals": "যন্ত্রপাতি ভাড়া",
        "fhMandiPrices": "স্থানীয় মান্ডির দাম",
        "fhLoading": "ডেটা লোড হচ্ছে...",
        "fhExp": "অভিজ্ঞতা",
        "fhRateRequired": "প্রয়োজনীয় হার",
        "fhProximity": "নৈকট্য",
        "fhLaborerBooked": "শ্রমিক বুক করা হয়েছে",
        "fhBooking": "বুকিং...",
        "fhBookLaborer": "শ্রমিক বুক করুন",
        "fhOwner": "মালিক",
        "fhRentalRate": "ভাড়ার হার",
        "fhLocation": "অবস্থান",
        "fhCurrentlyRented": "বর্তমানে ভাড়া দেওয়া আছে",
        "fhRentEquipment": "যন্ত্রপাতি ভাড়া নিন",
        "fhRenting": "ভাড়া নিচ্ছি...",
        "fhMandiDesc": "নিচে স্থানীয় মান্ডির যাচাইকৃত দাম দেওয়া হলো।",
        "fhCropName": "ফসলের নাম",
        "fhSonipatMandi": "সোনিপথ মান্ডি",
        "fhNarelaMandi": "নরেলা মান্ডি",
        "fhRohtakMandi": "রোহতক মান্ডি",
        "fhDailyTrend": "দৈনিক প্রবণতা",
        "fhUpward": "▲ উপরে",
        "fhDownward": "▼ নিচে",
        "vsSecureGov": "নিরাপদ সরকারি API স্যান্ডবক্স",
        "vsTitle": "আধার পরিচয় যাচাইকরণ",
        "vsDesc": "উচ্চ ট্রাস্ট স্কোর এবং ভালো চাকরির জন্য OTP দিয়ে পরিচয় যাচাই করুন।",
        "vsWhyVerify": "পরিচয় যাচাই করবেন কেন?",
        "vsZeroScam": "শূন্য কেলেঙ্কারি প্ল্যাটফর্ম",
        "vsZeroScamDesc": "নিশ্চিত করে যে প্রতিটি ব্যবহারকারীর একটিই অ্যাকাউন্ট আছে।",
        "vsTrustScore": "ট্রাস্ট স্কোর বৃদ্ধি",
        "vsTrustScoreDesc": "আধার যাচাইকরণে ট্রাস্ট স্কোর তাৎক্ষণিকভাবে +২৫ পয়েন্ট বাড়ে।",
        "vsEmployerPriority": "নিয়োগকর্তার অগ্রাধিকার",
        "vsEmployerPriorityDesc": "যাচাইকৃত কর্মীরা নিয়োগকর্তাদের কাছে আগে উপস্থিত হয়।",
        "vsStep1": "ধাপ ১: ১২-অঙ্কের আধার দিন",
        "vsAadhaarNum": "আধার নম্বর",
        "vsAadhaarPlaceholder": "XXXX XXXX XXXX",
        "vsNoStore": "আমরা আধার সংরক্ষণ করি না। সরাসরি CIDR যাচাইকরণ।",
        "vsRequestOtp": "OTP অনুরোধ করুন",
        "vsStep2": "ধাপ ২: SMS OTP দিন",
        "vsOtpSent": "আপনার আধার-লিঙ্ক করা মোবাইল নম্বরে একটি কোড পাঠানো হয়েছে",
        "vsUseCode": "অনুকরণের জন্য কোড ব্যবহার করুন",
        "vsSimulate": "",
        "vs6DigitOtp": "৬-অঙ্কের OTP",
        "vsEnterOtpPlaceholder": "৬-অঙ্কের OTP দিন",
        "vsGoBack": "ফিরে যান",
        "vsVerifyMatch": "যাচাই করুন এবং পরিচয় মেলান",
        "vsConnecting": "CIDR স্যান্ডবক্সের সাথে সংযুক্ত হচ্ছে",
        "vsInspecting": "বায়োমেট্রিক ডেটা এবং নাম যাচাই করা হচ্ছে...",
        "vsConfirmed": "আধার পরিচয় নিশ্চিত হয়েছে!",
        "vsCongrats": "অভিনন্দন! আপনার প্রোফাইলে সরকারি যাচাইকরণ ব্যাজ যোগ করা হয়েছে।",
        "vsBaseTrust": "মূল ট্রাস্ট স্কোর:",
        "vsNewTrust": "নতুন ট্রাস্ট স্কোর:",
        "vsReturn": "ড্যাশবোর্ডে ফিরে যান",
        "vsErrAadhaarLen": "আধার নম্বর ১২ অঙ্কের হতে হবে।",
        "vsErrReqOtp": "OTP অনুরোধ ব্যর্থ",
        "vsErrOtpLen": "OTP ৬ অঙ্কের হতে হবে।",
        "vsErrInvalidOtp": "ভুল OTP",
        "appTopBanner": "সরকারি প্রযুক্তি উদ্যোগ স্যান্ডবক্স। ১০০% নিরাপদ।",
        "appLogoSubtitle": "সরকারি কর্মসংস্থান ইকোসিস্টেম"
    },
    "ta": {
        "jsExplore": "உள்ளூர் வேலை வாய்ப்புகளைத் தேடுங்கள்",
        "jsExploreDesc": "தினசரி கூலி, விவசாயம் மற்றும் கைவினைஞர் வேலைகளைத் தேடி விண்ணப்பிக்கவும்.",
        "jsAadhaarInspected": "100% ஆதார் சரிபார்க்கப்பட்டது",
        "jsSearchPlaceholder": "வேலை வகை, முதலாளி அல்லது இடத்தைத் தேடவும்...",
        "jsListening": "கேட்கிறது...",
        "jsVerifiedEmployers": "சரிபார்க்கப்பட்ட முதலாளிகள் மட்டும்",
        "catAll": "அனைத்தும்",
        "catAgriculture": "விவசாயம்",
        "catCarpenter": "தச்சர்",
        "catPainter": "பெயிண்டர்",
        "catElectrician": "எலக்ட்ரீஷியன்",
        "catPlumber": "பிளம்பர்",
        "catDriver": "ஓட்டுநர்",
        "catDailyWage": "தினசரி கூலி",
        "jsLoadingJobs": "வேலைகள் ஏற்றப்படுகின்றன...",
        "jsEmployerTrust": "முதலாளி நம்பிக்கை",
        "jsEmployer": "முதலாளி",
        "jsGovtOk": "அரசு அங்கீகாரம்",
        "jsAway": "தொலைவில்",
        "jsAppSubmitted": "விண்ணப்பம் சமர்ப்பிக்கப்பட்டது",
        "jsStopRecording": "பதிவை நிறுத்து",
        "jsApplyVoice": "குரல் மூலம் விண்ணப்பிக்கவும்",
        "jsApplyManual": "கைமுறையாக விண்ணப்பிக்கவும்",
        "jsSayToApply": '"நான் விண்ணப்பிக்க விரும்புகிறேன்" என்று கூறவும் அல்லது உங்கள் தகுதிகளைத் தெரிவிக்கவும்...',
        "jsNoJobsFound": "வேலைகள் எதுவும் கிடைக்கவில்லை. தேடலை மாற்றவும்.",
        "jsFailedToFetch": "வேலைகளைப் பெறுவதில் தோல்வி",
        "jsFailedToApply": "விண்ணப்பிப்பதில் தோல்வி",
        "fhTitle": "ஸ்மார்ட் வேளாண்மை மையம்",
        "fhDesc": "சரிபார்க்கப்பட்ட விவசாயத் தொழிலாளர்களைக் கண்டறியவும், இயந்திரங்களை வாடகைக்கு எடுக்கவும், சந்தை விலைகளைச் சரிபார்க்கவும்.",
        "fhSeasonal": "பருவகால தேவை சரிபார்க்கப்பட்டது",
        "fhWeatherAdv": "வானிலை ஆலோசனை",
        "fhClearSky": "தெளிவான வானம் • அறுவடைக்கு ஏற்றது",
        "fhNoRainfall": "அடுத்த 5 நாட்களுக்கு மழை பெய்ய வாய்ப்பில்லை. அறுவடையை முடிக்கவும்.",
        "fhPriceStabilization": "விலை நிலைத்தன்மை உத்தரவாதம்",
        "fhPriceDesc": "ஜீவன்சேது ஸ்மார்ட் ஒப்பந்தங்கள் மூலம் விலைகளை கட்டுப்படுத்துகிறது.",
        "fhHireLaborers": "விவசாயத் தொழிலாளர்களை வேலைக்கு அமர்த்தவும்",
        "fhEquipmentRentals": "உபகரணங்கள் வாடகை",
        "fhMandiPrices": "உள்ளூர் மண்டி விலைகள்",
        "fhLoading": "தரவு ஏற்றப்படுகிறது...",
        "fhExp": "அனுபவம்",
        "fhRateRequired": "தேவையான கட்டணம்",
        "fhProximity": "அருகாமையில்",
        "fhLaborerBooked": "தொழிலாளி பதிவு செய்யப்பட்டார்",
        "fhBooking": "பதிவு செய்யப்படுகிறது...",
        "fhBookLaborer": "தொழிலாளியை பதிவு செய்",
        "fhOwner": "உரிமையாளர்",
        "fhRentalRate": "வாடகை கட்டணம்",
        "fhLocation": "இடம்",
        "fhCurrentlyRented": "தற்போது வாடகைக்கு விடப்பட்டுள்ளது",
        "fhRentEquipment": "உபகரணங்களை வாடகைக்கு எடு",
        "fhRenting": "வாடகைக்கு எடுக்கப்படுகிறது...",
        "fhMandiDesc": "கீழே உள்ளூர் சந்தைகளின் சரிபார்க்கப்பட்ட விலைகள் உள்ளன.",
        "fhCropName": "பயிரின் பெயர்",
        "fhSonipatMandi": "சோனிபட் மண்டி",
        "fhNarelaMandi": "நரேலா மண்டி",
        "fhRohtakMandi": "ரோஹ்தக் மண்டி",
        "fhDailyTrend": "தினசரி போக்கு",
        "fhUpward": "▲ மேல்நோக்கி",
        "fhDownward": "▼ கீழ்நோக்கி",
        "vsSecureGov": "பாதுகாப்பான அரசு API சாண்ட்பாக்ஸ்",
        "vsTitle": "ஆதார் அடையாள சரிபார்ப்பு",
        "vsDesc": "அதிக நம்பிக்கை மதிப்பெண்ணுக்கு OTP மூலம் உங்கள் அடையாளத்தை சரிபார்க்கவும்.",
        "vsWhyVerify": "அடையாளத்தை ஏன் சரிபார்க்க வேண்டும்?",
        "vsZeroScam": "பூஜ்ஜிய மோசடி தளம்",
        "vsZeroScamDesc": "ஒவ்வொரு பயனருக்கும் ஒரு கணக்கு மட்டுமே இருப்பதை உறுதி செய்கிறது.",
        "vsTrustScore": "நம்பிக்கை மதிப்பெண் அதிகரிப்பு",
        "vsTrustScoreDesc": "ஆதார் சரிபார்ப்பு உடனடியாக +25 புள்ளிகளை சேர்க்கிறது.",
        "vsEmployerPriority": "முதலாளி முன்னுரிமை",
        "vsEmployerPriorityDesc": "சரிபார்க்கப்பட்ட தொழிலாளர்கள் முதலில் தோன்றுவார்கள்.",
        "vsStep1": "படி 1: 12-இலக்க ஆதாரை உள்ளிடவும்",
        "vsAadhaarNum": "ஆதார் எண்",
        "vsAadhaarPlaceholder": "XXXX XXXX XXXX",
        "vsNoStore": "நாங்கள் ஆதாரை சேமிப்பதில்லை. நேரடி CIDR சரிபார்ப்பு.",
        "vsRequestOtp": "OTP கோரிக்கை",
        "vsStep2": "படி 2: SMS OTP உள்ளிடவும்",
        "vsOtpSent": "உங்கள் ஆதார் இணைக்கப்பட்ட மொபைல் எண்ணுக்கு குறியீடு அனுப்பப்பட்டுள்ளது",
        "vsUseCode": "உருவகப்படுத்த குறியீட்டைப் பயன்படுத்தவும்",
        "vsSimulate": "",
        "vs6DigitOtp": "6-இலக்க OTP",
        "vsEnterOtpPlaceholder": "6-இலக்க OTP ஐ உள்ளிடவும்",
        "vsGoBack": "திரும்பிச் செல்",
        "vsVerifyMatch": "சரிபார்த்து ஒப்பிடவும்",
        "vsConnecting": "CIDR சாண்ட்பாக்ஸுடன் இணைகிறது",
        "vsInspecting": "பயோமெட்ரிக் தரவு சரிபார்க்கப்படுகிறது...",
        "vsConfirmed": "ஆதார் அடையாளம் உறுதிப்படுத்தப்பட்டது!",
        "vsCongrats": "வாழ்த்துக்கள்! உங்கள் சுயவிவரத்தில் அரசு சரிபார்ப்பு பேட்ஜ் சேர்க்கப்பட்டுள்ளது.",
        "vsBaseTrust": "அடிப்படை நம்பிக்கை மதிப்பெண்:",
        "vsNewTrust": "புதிய நம்பிக்கை மதிப்பெண்:",
        "vsReturn": "டாஷ்போர்டுக்குத் திரும்பு",
        "vsErrAadhaarLen": "ஆதார் எண் சரியாக 12 இலக்கங்களைக் கொண்டிருக்க வேண்டும்.",
        "vsErrReqOtp": "OTP கோரிக்கை தோல்வி",
        "vsErrOtpLen": "OTP 6 இலக்கங்களைக் கொண்டிருக்க வேண்டும்.",
        "vsErrInvalidOtp": "தவறான OTP",
        "appTopBanner": "அதிகாரப்பூர்வ அரசு தொழில்நுட்ப முயற்சி. 100% பாதுகாப்பானது.",
        "appLogoSubtitle": "அரசு வேலைவாய்ப்பு சுற்றுச்சூழல்"
    },
    "te": {
        "jsExplore": "స్థానిక పని అవకాశాలను కనుగొనండి",
        "jsExploreDesc": "రోజువారీ వేతనం, వ్యవసాయం మరియు చేతివృత్తుల పనులను కనుగొని దరఖాస్తు చేయండి.",
        "jsAadhaarInspected": "100% ఆధార్ ధృవీకరించబడింది",
        "jsSearchPlaceholder": "పని రకం, యజమాని లేదా స్థానాన్ని శోధించండి...",
        "jsListening": "వింటుంది...",
        "jsVerifiedEmployers": "ధృవీకరించబడిన యజమానులు మాత్రమే",
        "catAll": "అన్నీ",
        "catAgriculture": "వ్యవసాయం",
        "catCarpenter": "వడ్రంగి",
        "catPainter": "పెయింటర్",
        "catElectrician": "ఎలక్ట్రీషియన్",
        "catPlumber": "ప్లంబర్",
        "catDriver": "డ్రైవర్",
        "catDailyWage": "రోజువారీ వేతనం",
        "jsLoadingJobs": "ఉద్యోగాలు లోడ్ అవుతున్నాయి...",
        "jsEmployerTrust": "యజమాని నమ్మకం",
        "jsEmployer": "యజమాని",
        "jsGovtOk": "ప్రభుత్వం ఆమోదించబడింది",
        "jsAway": "దూరంగా",
        "jsAppSubmitted": "దరఖాస్తు సమర్పించబడింది",
        "jsStopRecording": "రికార్డింగ్ ఆపు",
        "jsApplyVoice": "వాయిస్ ద్వారా దరఖాస్తు చేయండి",
        "jsApplyManual": "మాన్యువల్ అప్లై",
        "jsSayToApply": '"నేను దరఖాస్తు చేయాలనుకుంటున్నాను" అని చెప్పండి లేదా మీ అర్హతలను తెలపండి...',
        "jsNoJobsFound": "ఉద్యోగాలు ఏవీ కనుగొనబడలేదు. దయచేసి శోధనను మార్చండి.",
        "jsFailedToFetch": "ఉద్యోగాలు పొందడంలో విఫలమైంది",
        "jsFailedToApply": "దరఖాస్తు చేయడంలో విఫలమైంది",
        "fhTitle": "స్మార్ట్ అగ్రికల్చర్ హబ్",
        "fhDesc": "ధృవీకరించబడిన వ్యవసాయ కార్మికులను కనుగొనండి, యంత్రాలను అద్దెకు తీసుకోండి, మార్కెట్ ధరలను తనిఖీ చేయండి.",
        "fhSeasonal": "కాలానుగుణ డిమాండ్ ధృవీకరించబడింది",
        "fhWeatherAdv": "వాతావరణ సలహా",
        "fhClearSky": "స్పష్టమైన ఆకాశం • కోతకు అనుకూలం",
        "fhNoRainfall": "తదుపరి 5 రోజులు వర్షం పడే అవకాశం లేదు. కోత పూర్తి చేయండి.",
        "fhPriceStabilization": "ధర స్థిరీకరణ హామీ",
        "fhPriceDesc": "జీవన్‌సేతు స్మార్ట్ ఒప్పందాల ద్వారా ధరలను నియంత్రిస్తుంది.",
        "fhHireLaborers": "వ్యవసాయ కార్మికులను నియమించుకోండి",
        "fhEquipmentRentals": "పరికరాల అద్దె",
        "fhMandiPrices": "స్థానిక మార్కెట్ ధరలు",
        "fhLoading": "డేటా లోడ్ అవుతోంది...",
        "fhExp": "అనుభవం",
        "fhRateRequired": "అవసరమైన రేటు",
        "fhProximity": "సామీప్యత",
        "fhLaborerBooked": "కార్మికుడు బుక్ చేయబడ్డాడు",
        "fhBooking": "బుకింగ్...",
        "fhBookLaborer": "కార్మికుడిని బుక్ చేయండి",
        "fhOwner": "యజమాని",
        "fhRentalRate": "అద్దె రేటు",
        "fhLocation": "స్థానం",
        "fhCurrentlyRented": "ప్రస్తుతం అద్దెకు ఇవ్వబడింది",
        "fhRentEquipment": "పరికరాలను అద్దెకు తీసుకోండి",
        "fhRenting": "అద్దెకు తీసుకుంటున్నాము...",
        "fhMandiDesc": "క్రింద స్థానిక మార్కెట్ల ధృవీకరించబడిన ధరలు ఉన్నాయి.",
        "fhCropName": "పంట పేరు",
        "fhSonipatMandi": "సోనిపట్ మండి",
        "fhNarelaMandi": "నరేలా మండి",
        "fhRohtakMandi": "రోహ్తక్ మండి",
        "fhDailyTrend": "రోజువారీ ధోరణి",
        "fhUpward": "▲ పైకి",
        "fhDownward": "▼ క్రిందికి",
        "vsSecureGov": "సురక్షిత ప్రభుత్వ API శాండ్‌బాక్స్",
        "vsTitle": "ఆధార్ గుర్తింపు ధృవీకరణ",
        "vsDesc": "అధిక ట్రస్ట్ స్కోర్ కోసం OTP ద్వారా మీ గుర్తింపును ధృవీకరించండి.",
        "vsWhyVerify": "గుర్తింపును ఎందుకు ధృవీకరించాలి?",
        "vsZeroScam": "జీరో స్కామ్ ప్లాట్‌ఫారమ్",
        "vsZeroScamDesc": "ప్రతి వినియోగదారుకు ఒకే ఖాతా ఉందని నిర్ధారిస్తుంది.",
        "vsTrustScore": "ట్రస్ట్ స్కోర్ పెరుగుదల",
        "vsTrustScoreDesc": "ఆధార్ ధృవీకరణ వెంటనే +25 పాయింట్లను జోడిస్తుంది.",
        "vsEmployerPriority": "యజమాని ప్రాధాన్యత",
        "vsEmployerPriorityDesc": "ధృవీకరించబడిన కార్మికులు మొదట కనిపిస్తారు.",
        "vsStep1": "దశ 1: 12-అంకెల ఆధార్‌ను నమోదు చేయండి",
        "vsAadhaarNum": "ఆధార్ సంఖ్య",
        "vsAadhaarPlaceholder": "XXXX XXXX XXXX",
        "vsNoStore": "మేము ఆధార్‌ను నిల్వ చేయము. ప్రత్యక్ష CIDR ధృవీకరణ.",
        "vsRequestOtp": "OTP అభ్యర్థన",
        "vsStep2": "దశ 2: SMS OTP నమోదు చేయండి",
        "vsOtpSent": "మీ ఆధార్ లింక్ చేసిన మొబైల్ నంబర్‌కు కోడ్ పంపబడింది",
        "vsUseCode": "అనుకరించడానికి కోడ్‌ను ఉపయోగించండి",
        "vsSimulate": "",
        "vs6DigitOtp": "6-అంకెల OTP",
        "vsEnterOtpPlaceholder": "6-అంకెల OTP నమోదు చేయండి",
        "vsGoBack": "వెనక్కి వెళ్ళు",
        "vsVerifyMatch": "ధృవీకరించి సరిపోల్చండి",
        "vsConnecting": "CIDR శాండ్‌బాక్స్‌కు కనెక్ట్ అవుతోంది",
        "vsInspecting": "బయోమెట్రిక్ డేటా తనిఖీ చేయబడుతోంది...",
        "vsConfirmed": "ఆధార్ గుర్తింపు నిర్ధారించబడింది!",
        "vsCongrats": "అభినందనలు! మీ ప్రొఫైల్‌కు ప్రభుత్వ ధృవీకరణ బ్యాజ్ జోడించబడింది.",
        "vsBaseTrust": "బేస్ ట్రస్ట్ స్కోర్:",
        "vsNewTrust": "కొత్త ట్రస్ట్ స్కోర్:",
        "vsReturn": "డాష్‌బోర్డ్‌కు తిరిగి వెళ్ళు",
        "vsErrAadhaarLen": "ఆధార్ సంఖ్య సరిగ్గా 12 అంకెలు ఉండాలి.",
        "vsErrReqOtp": "OTP అభ్యర్థన విఫలమైంది",
        "vsErrOtpLen": "OTP 6 అంకెలు ఉండాలి.",
        "vsErrInvalidOtp": "చెల్లని OTP",
        "appTopBanner": "అధికారిక ప్రభుత్వ సాంకేతిక చొరవ. 100% సురక్షితం.",
        "appLogoSubtitle": "ప్రభుత్వ ఉపాధి పర్యావరణ వ్యవస్థ"
    }
}

with open(translations_file, "r", encoding="utf-8") as f:
    content = f.read()

# Replace the English placeholder keys in the other languages with the real translated keys
for lang in ['gu', 'pa', 'bn', 'ta', 'te']:
    # We need to find the block for the language and replace the english values with the translated ones
    # Since I appended them using regex earlier, they exist in the file as `key: 'EnglishValue',`
    # Let's extract the block
    pattern_lang_block = re.compile(rf"({lang}:\s*{{)(.*?)(\n\s*}},|\n\s*}}\s*(?:export|$))", re.DOTALL)
    
    match = pattern_lang_block.search(content)
    if match:
        block_start = match.group(1)
        block_content = match.group(2)
        block_end = match.group(3)
        
        # Replace each key's value in this block
        for k, v in new_translations[lang].items():
            # Escape quotes
            v_escaped = v.replace("'", "\\'")
            
            # The current line might look like: `    jsExplore: 'Explore Local Work Opportunities',`
            # We want to replace whatever string is there with the new v_escaped
            key_pattern = rf"(\b{k}:\s*')([^']*)(')"
            block_content = re.sub(key_pattern, rf"\g<1>{v_escaped}\g<3>", block_content)
            
        content = content[:match.start()] + block_start + block_content + block_end + content[match.end():]

with open(translations_file, "w", encoding="utf-8") as f:
    f.write(content)

print("Translations for all remaining languages successfully updated in translations.ts!")
